name: On PR

on:
  pull_request:
    types: [opened, edited]

permissions:
  pull-requests: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  sheriff:
    runs-on: ubuntu-latest
    steps:
      - uses: teneplaysofficial/sheriff@fe16e6cbcf9d1db3523f7f0f63cfba59db59a5f6 # v5
